name: primeira-pipeline
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "hello wold"
      - name: "Segunda ação"        
        run: |
          echo "Voce Criou o seu primeiro workflow"
          echo "Parabens !!"
      - name: "Scrip Python"
        run: |
          variavel = "Hello python"
          print(variavel)
        shell: python
  segundo-job:
    name: "instalacao do ambiente nodejs"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - name: "verificao da versao nodejs atual"
        run: node --version
      - name: "Definicao da versao 20.13.1 do nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
      - name: "verificao da versao nodejs atual"
        run: node --version
